### ISSUE TITLE
Error #04

### ISSUE THREAD

**Issue by nataliedavis** [NetLogo/R-Extension#21] opened 2020-07-15 11:03 UTC
I just updated R (v4.0.2) and Netlogo (v6.1.1) and I am now getting the Error #04 "Error initializing R extension." I have updated the user.properties file as directed to include the new paths, and rJava is installed and can be loaded in R.

Happy to provide any additional information if needed.

**Comment by LaCuneta** [comment] 2020-10-05 14:32
Hey Natalie,

Sorry you ran into this trouble with the R extension, and sorry for the delayed reply here.

Error #04 indicates that the JRI path isn't set correct. 

First, make sure you're editing the right `user.properties` file, the R extension that comes with NetLogo 6.1.1 changed the location of the file from prior versions.  Check [the directions for the operating system-specific path](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#configuring-the-r-extension).

Second, [double check the path for `jri.home.paths` you set in the file inside of R](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#determining-rhome-and-jrihomepaths).

Third, if you are on Windows, make sure you have [installed the VC++ 2013 runtime](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#windows-specific-installation-steps) and [configured your `PATH` environment variable to include the R executables folder](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#configuring-the-path).

I hope that helps.  If you still have problems getting it running let me know the operating system you're using and I can try to come up with some more things to try.

**Comment by LaCuneta** [comment] 2020-10-16 17:54
Closing this for now, but feel free to reply on this issue if you need more assistance.

**Closed as completed by LaCuneta** 2020-10-16 17:54 UTC

**Comment by Matheus-Santos-Araujo** [comment] 2021-05-03 03:50
Hello, I have the same problem in Windows 10. The user.properties file has the correct path and is the real one. What is the difference between error #4 and error #2? Because when the JRI is in the wrong path, it accuses error #2 and when everything is perfect in path, error #4. Which leads me to think that the error is not in JRI path, but in extension or JAVA enviromment or R.

**Comment by LaCuneta** [comment] 2021-05-03 17:54
@Matheus-Santos-Araujo [The docs explain a bit about the error codes](http://ccl.northwestern.edu/netlogo/docs/r.html#specific-error-code-list)

> Error #02: Cannot find rJava/JRI. The R Extension was unable to locate your installation of rJava. Some steps to resolve:
> Ensure that rJava (0.9-8 or later) is installed in R. Ensure that it’s installed either system-wide or for you as a user
> Ensure that your configuration points to the proper rJava location. If you have a user.properties file, ensure that jri.home.paths includes the path given by R when you run system.file("jri",package="rJava")

> Error #04: Error in R-Extension. This is an unknown initialization error. Ensure that you are running R 3.0.0 or later and have the rJava extension installed (version 0.9-8 or later). 

Unfortunately there are a variety of things Error #04 can describe.  One trying to load the libraries JRI.jar, REngine.jar, and JRIEngine.jar, and then it's attempting to load the "x64" or "i386" from the JRI path as well.  Those should all be present in the JRI path, and if not it'll definitely cause the error.  Another thing it would be raised for is when actually trying to load code from those library files, which could be caused by a version mismatch or permissions issue.  The error code is also used in a couple other places.  If you can post the full Error #04 you're seeing I might be able to track it down further.

**Comment by edmizac** [comment] 2023-07-05 14:49
Hi, 

First of all sorry bringing my questions to another issues, but I think this one is worth noting. 

As mentioned [here](https://github.com/NetLogo/R-Extension/issues/9), I managed to make the R extension run on my personal notebook. However, yesterday I uninsalled *older*(!!) R versions I had (R 3.something) to free some space. To my surprise, I got the error 04 again (the same one from this issue), but slightly different: 

![image](https://github.com/NetLogo/R-Extension/assets/72988462/127aeb55-7538-4de9-99cc-33801efed283)

And this when I open the .nlogo file:
![image](https://github.com/NetLogo/R-Extension/assets/72988462/86f3ff39-ad4a-4cf4-bbdc-a63c3a8de515)


I am trying to be logical and understand what happened, but sincerely... 
I have been stuck to error 04 in other machines too #29 

Here's my info:

```
> Sys.getenv("R_HOME")
[1] "C:/PROGRA~1/R/R-42~1.1"
> system.file("jri", package = "rJava")
[1] "C:/Program Files/R/R-4.2.1/library/rJava/jri"
```

My user.properties:
```
r.home=C:/PROGRA~1/R/R-42~1.1            # was working, does not work anymore
#r.home=C:/Program Files/R/R-4.2.1          # does not work
jri.home.paths=C:/Program Files/R/R-4.2.1/library/rJava/jri
r.lib.paths=C:/Program Files/R/R-4.2.1/library

```

My environmental vars:
![image](https://github.com/NetLogo/R-Extension/assets/72988462/35ff5a3e-d542-4259-9ee3-c2664c0631d9)


Thank you.



**EDIT:**

I created a R_HOME variable in the bottom section of my environmental variables (valid for all users) and it got back to work, but then I got the same problem I cited [here](https://github.com/NetLogo/R-Extension/issues/9). I followed the same solution I stated there (added the \bin\x64 to PATH) and the extension started working again.

I am starting to believe that most of the issues are related to user permissions on Windows...

Thank you.
